version: '3.9'

services:

  b_app:
    image: diploma_back
    build: ./
    ports:
      - '8080:8080'
    depends_on:
      - postgres


  postgres:
    image: postgres:13.3
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: "kvs_db"
      POSTGRES_USER: "kvs"
      POSTGRES_PASSWORD: "123"
    ports:
      - '5432:5432'
    volumes:
      - .:/docker-entrypoint-initdb.d

